// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiuimbjhxbuvtlblbbkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pdWltYmpoeGJ1dnRsYmxiYmtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDk1NDUsImV4cCI6MjA3MDA4NTU0NX0.b7DHW3arWn_Vy4PdSKqLotqIonpgh5bVCoClybQWFwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});